//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Notice: Use of the service proxies that accompany this notice is subject to
//            the terms and conditions of the license agreement located at
//            http://go.microsoft.com/fwlink/?LinkID=202740
//            If you do not agree to these terms you may not use this content.
namespace DnB {
    using System;
    using System.Collections.Generic;
    using System.Data.Services.Client;
    using System.Net;
    using System.IO;
    
    
    public partial class CleanseMatchByNameAddressEntity {
        
        private String _DUNSNumber;
        
        private String _Company;
        
        private String _Address;
        
        private String _City;
        
        private String _State;
        
        private String _ZipCode;
        
        private String _CountryISOCode;
        
        private String _Phone;
        
        private String _ConfidenceCode;
        
        private String _MatchGrade;
        
        private String _TransactionFlag;
        
        private String _TransactionStatus;
        
        private String _TransactionStatusCode;
        
        public String DUNSNumber {
            get {
                return this._DUNSNumber;
            }
            set {
                this._DUNSNumber = value;
            }
        }
        
        public String Company {
            get {
                return this._Company;
            }
            set {
                this._Company = value;
            }
        }
        
        public String Address {
            get {
                return this._Address;
            }
            set {
                this._Address = value;
            }
        }
        
        public String City {
            get {
                return this._City;
            }
            set {
                this._City = value;
            }
        }
        
        public String State {
            get {
                return this._State;
            }
            set {
                this._State = value;
            }
        }
        
        public String ZipCode {
            get {
                return this._ZipCode;
            }
            set {
                this._ZipCode = value;
            }
        }
        
        public String CountryISOCode {
            get {
                return this._CountryISOCode;
            }
            set {
                this._CountryISOCode = value;
            }
        }
        
        public String Phone {
            get {
                return this._Phone;
            }
            set {
                this._Phone = value;
            }
        }
        
        public String ConfidenceCode {
            get {
                return this._ConfidenceCode;
            }
            set {
                this._ConfidenceCode = value;
            }
        }
        
        public String MatchGrade {
            get {
                return this._MatchGrade;
            }
            set {
                this._MatchGrade = value;
            }
        }
        
        public String TransactionFlag {
            get {
                return this._TransactionFlag;
            }
            set {
                this._TransactionFlag = value;
            }
        }
        
        public String TransactionStatus {
            get {
                return this._TransactionStatus;
            }
            set {
                this._TransactionStatus = value;
            }
        }
        
        public String TransactionStatusCode {
            get {
                return this._TransactionStatusCode;
            }
            set {
                this._TransactionStatusCode = value;
            }
        }
    }
    
    public partial class DnContainer : System.Data.Services.Client.DataServiceContext {
        
        public DnContainer(Uri serviceRoot) : 
                base(serviceRoot) {
        }
        
        /// <summary>
        /// </summary>
        /// <param name="Name">Business Name Or Executive Name Sample Values : Dell Inc.</param>
        /// <param name="StreetAddress">Business Street Address Sample Values : 1 Dell Way</param>
        /// <param name="City">City Sample Values : Round Rock</param>
        /// <param name="State">State Sample Values : TX</param>
        /// <param name="PostalCode">PostalCode Sample Values : 78682</param>
        /// <param name="CountryCode">Country Code Sample Values : US</param>
        /// <param name="PhoneNumber">PhoneNumber Sample Values : 5123384400</param>
        /// <param name="MinimumConfidence">ConfidenceThreshold - Should be 4 or above Sample Values : 8</param>
        public DataServiceQuery<CleanseMatchByNameAddressEntity> CompanyMatchByNameAddress(String Name, String StreetAddress, String City, String State, String PostalCode, String CountryCode, String PhoneNumber, String MinimumConfidence) {
            if ((Name == null)) {
                throw new System.ArgumentNullException("Name", "Name value cannot be null");
            }
            if ((CountryCode == null)) {
                throw new System.ArgumentNullException("CountryCode", "CountryCode value cannot be null");
            }
            DataServiceQuery<CleanseMatchByNameAddressEntity> query;
            query = base.CreateQuery<CleanseMatchByNameAddressEntity>("CompanyMatchByNameAddress");
            if ((Name != null)) {
                query = query.AddQueryOption("Name", string.Concat("\'", System.Uri.EscapeDataString(Name), "\'"));
            }
            if ((StreetAddress != null)) {
                query = query.AddQueryOption("StreetAddress", string.Concat("\'", System.Uri.EscapeDataString(StreetAddress), "\'"));
            }
            if ((City != null)) {
                query = query.AddQueryOption("City", string.Concat("\'", System.Uri.EscapeDataString(City), "\'"));
            }
            if ((State != null)) {
                query = query.AddQueryOption("State", string.Concat("\'", System.Uri.EscapeDataString(State), "\'"));
            }
            if ((PostalCode != null)) {
                query = query.AddQueryOption("PostalCode", string.Concat("\'", System.Uri.EscapeDataString(PostalCode), "\'"));
            }
            if ((CountryCode != null)) {
                query = query.AddQueryOption("CountryCode", string.Concat("\'", System.Uri.EscapeDataString(CountryCode), "\'"));
            }
            if ((PhoneNumber != null)) {
                query = query.AddQueryOption("PhoneNumber", string.Concat("\'", System.Uri.EscapeDataString(PhoneNumber), "\'"));
            }
            if ((MinimumConfidence != null)) {
                query = query.AddQueryOption("MinimumConfidence", string.Concat("\'", System.Uri.EscapeDataString(MinimumConfidence), "\'"));
            }
            return query;
        }
    }
}
